### ISSUE TITLE
Can't flash hex file.

### ISSUE THREAD

**Issue by michaelpetri** [tltx/swc_usb#1]
Hi,

first of all, really nice project! I'm looking forward to upgrade my swc!

I've bought this ATmega32u4 (http://www.ebay.de/itm/301951688967?_trksid=p2057872.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT)

Now i'm trying to flash your hex file via avrdude on osx 10.11.6

first im not sure do i need to write into the flashmemory or the eeprom?

anyway i tried to verify both with the following two commands, both fail while verification:

**Flashmemory:**
```avrdude -p m32u4 -P /dev/cu.usbmodem1421 -c avr109 -U flash:v:$(pwd)/Desktop/swc_usb.hex```

**Output:**
```
Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e9587 (probably m32u4)
avrdude: verifying flash memory against /Users/michaelpetri/Desktop/swc_usb.hex:
avrdude: load data flash data from input file /Users/michaelpetri/Desktop/swc_usb.hex:
avrdude: input file /Users/michaelpetri/Desktop/swc_usb.hex auto detected as Intel Hex
avrdude: input file /Users/michaelpetri/Desktop/swc_usb.hex contains 6764 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.07s

avrdude: verifying ...
avrdude: verification error, first mismatch at byte 0x0000
         0x0c != 0x9b
avrdude: verification error; content mismatch

avrdude: safemode: Fuses OK (E:CB, H:D8, L:FF)

avrdude done.  Thank you.
```

**Eeprom:**
```avrdude -p m32u4 -P /dev/cu.usbmodem1421 -c avr109 -U eeprom:v:$(pwd)/Desktop/swc_usb.hex```

**Output:**
```
Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e9587 (probably m32u4)
avrdude: verifying eeprom memory against /Users/michaelpetri/Desktop/swc_usb.hex:
avrdude: load data eeprom data from input file /Users/michaelpetri/Desktop/swc_usb.hex:
avrdude: input file /Users/michaelpetri/Desktop/swc_usb.hex auto detected as Intel Hex
avrdude: ERROR: address 0x0410 out of range at line 65 of /Users/michaelpetri/Desktop/swc_usb.hex
avrdude: read from file '/Users/michaelpetri/Desktop/swc_usb.hex' failed

avrdude: safemode: Fuses OK (E:CB, H:D8, L:FF)

avrdude done.  Thank you.
```

Hope you can help me, if you need more details let me know!

Thanks in advance
Michael

**Comment by tltx** [comment]
Hi, nice to have someone trying out the project!

You should write to flash, use `-U flash:w:` to write. `-U flash:v:` is just verifying an extra time, you don't need to do that and if you haven't written the firmware first you are going to get a diff like you did.
 
This is the command I use:
`avrdude -c avr109 -p m32u4 -P /dev/tty.usbmodem411 -v -U flash:w:swc_usb.hex:i`


The board you are using seems to be a clone of [SparkFun Pro Micro](https://www.sparkfun.com/products/12640) and it does not have all the pins needed exposed on it. 

PB7 och PD6 is marked as "Not used" in the schematics and PD5 is hooked up to a LED for example. 

I recommend the [Teensy 2.0](https://www.pjrc.com/store/teensy.html), I haven't tried it myself but as far as I can see it has got everything you ned and it's small and I have heard good things about it.

Cheers 
Tore

**Comment by michaelpetri** [comment]
Hi,

thanks for your fast response and feedback. Can you confirm this pcb should work? 

https://www.amazon.de/XCSOURCE-Karte-Entwicklung-at90usb1286-ISP-Tastatur-U-TE502/dp/B01GRPF86C/ref=sr_1_1?rps=1&ie=UTF8&qid=1482098303&sr=8-1&keywords=teensy+2

Thanks
Michael

**Comment by michaelpetri** [comment]
Sry just read you comment again and updated the product link.

**Comment by tltx** [comment]
Hi, no the Teensy++ 2.0 has got another controller, maybe you could recompile for it. Look for a board with the ATMEGA32U4. [This looks like one](https://www.amazon.de/dp/B01N74RIKX/ref=sr_1_1?ie=UTF8&qid=1482098779&sr=8-1&keywords=teensy+2.0) (I don't speak German, so I'm not sure). The [Atmega32u4 Breakout Board](https://www.amazon.de/Adafruit-Atmega32u4-Breakout-Board/dp/B008AS3XHQ/ref=sr_1_1?ie=UTF8&qid=1482099192&sr=8-1&keywords=adafruit+296) looks really nice to, it has got all the pins marked out on the board with the right names.
