### ISSUE TITLE
Can't install the hex or any drivers.

### ISSUE THREAD

**Issue by Mclaneinc** [tltx/swc_usb#3]
Hi there, please try to excuse the lack of knowledge, I don't use python and never used one of these boards

No drivers came with the board

https://www.ebay.co.uk/itm/352722795632

I plug the board on to Windows 7  and I presume I press the button to stop the flashing but but using the suggested line for avrdude from your posts on here yields a cannot find \dev\usbmodem411 error.

Any help would be appreciated, the soldering I can do...

**Comment by tltx** [comment]
Hi
I think you can leave out -P /dev... or use -P usb or -P COM1

Best regards

Tore

ons 15 jan. 2020 kl. 19:41 skrev Mclaneinc <notifications@github.com>:

**Comment by Mclaneinc** [comment]
Hi Tore, thanks for the reply..

I've tried those and it complains of not finding a file called -v which is the next command line switch. I'm sure this is all down to some sort of Python serial port but my knowledge of python is very little. I managed to get pip to install pyserial and click but after that I have no idea how to use or make them work. In device manager I have no com port listed so presume its created by python??

As you can see that I'm quite lost, the soldering ok for me but I can't even get the hex file on the board :)

All I have is the board, a mini usb cable and plugged it in to my windows machine, it was flashing a lot so I pressed the switch, not sure if that was the right thing to do?

Paul.

**Comment by tltx** [comment]
You should be able to follow this instructions
https://www.pjrc.com/teensy/loader_win10.html


ons 15 jan. 2020 kl. 21:27 skrev Mclaneinc <notifications@github.com>:

**Comment by Mclaneinc** [comment]
Ah thank you...Just used it and seems to have worked...Brilliant...

Now to build the board and use the wildcard again after all these years..

Thank you so much Tore...

**Comment by Mclaneinc** [comment]
Well had to wait for a couple of parts but its all soldered up and WORKING...

I hate python tho :)

Thank you Tore for making my old wild card have a second use..

**Comment by tltx** [comment]
Just a tip. Remove the NiCd battery from the wild card and clean up the PCB, it's probably nasty. I replaced my battery with a super cap, that seems to work well.

**Comment by Mclaneinc** [comment]
Will do, must admit I'd did look but saw no leakage but it was a brief glance...

Thanks again for a wonderful little mod...

Paul.
